<script lang="ts">
	import { onMount } from 'svelte';
	import { DateTime } from 'luxon';
	import { copy } from 'svelte-copy';
	import * as Table from '$lib/components/ui/table';
	import type { PageServerData } from './$types';
	import { page } from '$app/stores';

	const host = $page.url.origin;

	export let data: PageServerData;
</script>

<svelte:head>
	<title>My profile</title>
</svelte:head>

<div class="bg-slate-800 rounded-xl p-3">
	<h1 class="text-center font-bold text-xl mb-4">Last 25 created URLs</h1>
	<Table.Root class="w-full">
		<Table.Caption
			>The last 25 URLs generated by you. Click the slug to copy the short URL.</Table.Caption
		>
		<Table.Header class="bg-slate-700">
			<Table.Row>
				<Table.Head class="w-[250px]">Slug</Table.Head>
				<Table.Head>URL</Table.Head>
				<Table.Head class="w-[200px]">When</Table.Head>
			</Table.Row>
		</Table.Header>
		<Table.Body class="bg-slate-900">
			{#each data.urls as url}
				<Table.Row>
					<Table.Cell class="font-medium"
						><p use:copy={`${host}/${url.slug}`} class="hover:text-blue-400 cursor-pointer">
							{url.slug}
						</p></Table.Cell
					>
					<Table.Cell
						><a href={url.location} target="_blank" class="hover:text-blue-500">{url.location}</a
						></Table.Cell
					>
					<Table.Cell
						>{DateTime.fromJSDate(url.created_at).setLocale('en-US').toRelative()}</Table.Cell
					>
				</Table.Row>
			{/each}
		</Table.Body>
	</Table.Root>
</div>
