<script lang="ts">
	import { onMount } from 'svelte';
	import { DateTime } from 'luxon';
	import { copy } from 'svelte-copy';
	import * as Table from '$lib/components/ui/table';
	import type { PageServerData } from './$types';
	import { page } from '$app/stores';

	const host = $page.url.origin;

	export let data: PageServerData;
</script>

<svelte:head>
	<title>My profile</title>
</svelte:head>

<!-- TODO: Add pagination and the ability to view more than just the last 25 URLs -->
<div class="bg-zinc-800 rounded-xl p-3">
	<h1 class="text-center font-bold text-xl mb-4">Last 25 created URLs</h1>
	{#if data.urls.length === 0}
		<h2 class="text-lg font-medium text-center">You haven't created any short URLs yet.</h2>
	{:else}
		<Table.Root class="w-full">
			<Table.Caption
				>The last 25 URLs generated by you. Click the slug to copy the short URL.</Table.Caption
			>
			<Table.Header class="bg-zinc-700">
				<Table.Row>
					<Table.Head
						class="w-[250px] py-2 px-4 rounded-tl border-r-[1px] border-zinc-500 border-dotted"
						><p>Slug</p></Table.Head
					>
					<Table.Head class="border-r-[1px] py-2 px-4 border-zinc-500 border-dotted"
						><p>URL</p></Table.Head
					>
					<Table.Head class="w-[200px] py-2 px-4 rounded-tr"><p>When</p></Table.Head>
				</Table.Row>
			</Table.Header>
			<Table.Body class="bg-zinc-900">
				{#each data.urls as url, i}
					<Table.Row>
						<Table.Cell
							class="font-medium py-2 px-4 border-r-[1px] border-zinc-500 border-dotted {i ===
							data.urls.length - 1
								? 'rounded-bl'
								: ''}"
							><p
								use:copy={`${host}/${url.slug}`}
								class="hover:text-blue-400 cursor-pointer transition-colors"
							>
								{url.slug}
							</p></Table.Cell
						>
						<Table.Cell class="font-medium py-2 px-4 border-r-[1px] border-zinc-500 border-dotted"
							><a href={url.location} target="_blank" class="hover:text-blue-400 transition-colors"
								>{url.location}</a
							></Table.Cell
						>
						<Table.Cell class="py-2 px-4 {i === data.urls.length - 1 ? 'rounded-br' : ''}"
							><p class="font-medium">
								{DateTime.fromJSDate(url.created_at).setLocale('en-US').toRelative()}
							</p></Table.Cell
						>
					</Table.Row>
				{/each}
			</Table.Body>
		</Table.Root>
	{/if}
</div>
